/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * JSONPlaceholder API
 * Free fake REST API for testing and prototyping
 * OpenAPI spec version: 1.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  Album,
  AlbumInput,
  AlbumPatch,
  GetAlbumsParams,
  Photo,
} from './api.generated.schemas'

import {axiosInstance} from '../axios'
import type {ErrorType, BodyType} from '../axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Returns a list of albums
 * @summary Get all albums
 */
export const getAlbums = (
  params?: GetAlbumsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Album[]>(
    {url: `/albums`, method: 'GET', params, signal},
    options,
  )
}

export const getGetAlbumsQueryKey = (params?: GetAlbumsParams) => {
  return [`/albums`, ...(params ? [params] : [])] as const
}

export const getGetAlbumsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAlbumsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbums>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlbums>>> = ({
    signal,
  }) => getAlbums(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getAlbums>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetAlbumsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAlbums>>
>
export type GetAlbumsQueryError = ErrorType<unknown>

export function useGetAlbums<
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetAlbumsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbums>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAlbums>>,
          TError,
          Awaited<ReturnType<typeof getAlbums>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbums<
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAlbumsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbums>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAlbums>>,
          TError,
          Awaited<ReturnType<typeof getAlbums>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetAlbums<
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAlbumsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbums>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get all albums
 */

export function useGetAlbums<
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAlbumsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbums>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAlbumsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetAlbumsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAlbumsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlbums>>> = ({
    signal,
  }) => getAlbums(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAlbums>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetAlbumsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAlbums>>
>
export type GetAlbumsSuspenseQueryError = ErrorType<unknown>

export function useGetAlbumsSuspense<
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetAlbumsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbumsSuspense<
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAlbumsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbumsSuspense<
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAlbumsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all albums
 */

export function useGetAlbumsSuspense<
  TData = Awaited<ReturnType<typeof getAlbums>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAlbumsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAlbumsSuspenseQueryOptions(params, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Creates a new album
 * @summary Create a new album
 */
export const createAlbum = (
  albumInput: BodyType<AlbumInput>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Album>(
    {
      url: `/albums`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: albumInput,
      signal,
    },
    options,
  )
}

export const getCreateAlbumMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAlbum>>,
    TError,
    {data: BodyType<AlbumInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAlbum>>,
  TError,
  {data: BodyType<AlbumInput>},
  TContext
> => {
  const mutationKey = ['createAlbum']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAlbum>>,
    {data: BodyType<AlbumInput>}
  > = (props) => {
    const {data} = props ?? {}

    return createAlbum(data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type CreateAlbumMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAlbum>>
>
export type CreateAlbumMutationBody = BodyType<AlbumInput>
export type CreateAlbumMutationError = ErrorType<unknown>

/**
 * @summary Create a new album
 */
export const useCreateAlbum = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAlbum>>,
      TError,
      {data: BodyType<AlbumInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createAlbum>>,
  TError,
  {data: BodyType<AlbumInput>},
  TContext
> => {
  const mutationOptions = getCreateAlbumMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Returns a single album
 * @summary Get an album by ID
 */
export const getAlbumById = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Album>(
    {url: `/albums/${id}`, method: 'GET', signal},
    options,
  )
}

export const getGetAlbumByIdQueryKey = (id?: number) => {
  return [`/albums/${id}`] as const
}

export const getGetAlbumByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlbumById>>> = ({
    signal,
  }) => getAlbumById(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getAlbumById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetAlbumByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAlbumById>>
>
export type GetAlbumByIdQueryError = ErrorType<null>

export function useGetAlbumById<
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAlbumById>>,
          TError,
          Awaited<ReturnType<typeof getAlbumById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbumById<
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAlbumById>>,
          TError,
          Awaited<ReturnType<typeof getAlbumById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetAlbumById<
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get an album by ID
 */

export function useGetAlbumById<
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAlbumByIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetAlbumByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlbumById>>> = ({
    signal,
  }) => getAlbumById(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAlbumById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetAlbumByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAlbumById>>
>
export type GetAlbumByIdSuspenseQueryError = ErrorType<null>

export function useGetAlbumByIdSuspense<
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbumByIdSuspense<
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbumByIdSuspense<
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get an album by ID
 */

export function useGetAlbumByIdSuspense<
  TData = Awaited<ReturnType<typeof getAlbumById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAlbumByIdSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Updates an existing album (replaces all fields)
 * @summary Update an album
 */
export const updateAlbum = (
  id: number,
  albumInput: BodyType<AlbumInput>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<Album>(
    {
      url: `/albums/${id}`,
      method: 'PUT',
      headers: {'Content-Type': 'application/json'},
      data: albumInput,
    },
    options,
  )
}

export const getUpdateAlbumMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAlbum>>,
    TError,
    {id: number; data: BodyType<AlbumInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAlbum>>,
  TError,
  {id: number; data: BodyType<AlbumInput>},
  TContext
> => {
  const mutationKey = ['updateAlbum']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAlbum>>,
    {id: number; data: BodyType<AlbumInput>}
  > = (props) => {
    const {id, data} = props ?? {}

    return updateAlbum(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type UpdateAlbumMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAlbum>>
>
export type UpdateAlbumMutationBody = BodyType<AlbumInput>
export type UpdateAlbumMutationError = ErrorType<unknown>

/**
 * @summary Update an album
 */
export const useUpdateAlbum = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAlbum>>,
      TError,
      {id: number; data: BodyType<AlbumInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAlbum>>,
  TError,
  {id: number; data: BodyType<AlbumInput>},
  TContext
> => {
  const mutationOptions = getUpdateAlbumMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Updates specific fields of an existing album
 * @summary Partially update an album
 */
export const patchAlbum = (
  id: number,
  albumPatch: BodyType<AlbumPatch>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<Album>(
    {
      url: `/albums/${id}`,
      method: 'PATCH',
      headers: {'Content-Type': 'application/json'},
      data: albumPatch,
    },
    options,
  )
}

export const getPatchAlbumMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchAlbum>>,
    TError,
    {id: number; data: BodyType<AlbumPatch>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchAlbum>>,
  TError,
  {id: number; data: BodyType<AlbumPatch>},
  TContext
> => {
  const mutationKey = ['patchAlbum']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchAlbum>>,
    {id: number; data: BodyType<AlbumPatch>}
  > = (props) => {
    const {id, data} = props ?? {}

    return patchAlbum(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type PatchAlbumMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAlbum>>
>
export type PatchAlbumMutationBody = BodyType<AlbumPatch>
export type PatchAlbumMutationError = ErrorType<unknown>

/**
 * @summary Partially update an album
 */
export const usePatchAlbum = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchAlbum>>,
      TError,
      {id: number; data: BodyType<AlbumPatch>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchAlbum>>,
  TError,
  {id: number; data: BodyType<AlbumPatch>},
  TContext
> => {
  const mutationOptions = getPatchAlbumMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Deletes an album
 * @summary Delete an album
 */
export const deleteAlbum = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>({url: `/albums/${id}`, method: 'DELETE'}, options)
}

export const getDeleteAlbumMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAlbum>>,
    TError,
    {id: number},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAlbum>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationKey = ['deleteAlbum']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAlbum>>,
    {id: number}
  > = (props) => {
    const {id} = props ?? {}

    return deleteAlbum(id, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type DeleteAlbumMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAlbum>>
>

export type DeleteAlbumMutationError = ErrorType<unknown>

/**
 * @summary Delete an album
 */
export const useDeleteAlbum = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAlbum>>,
      TError,
      {id: number},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAlbum>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationOptions = getDeleteAlbumMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Returns all photos for a specific album
 * @summary Get photos for an album
 */
export const getAlbumPhotos = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Photo[]>(
    {url: `/albums/${id}/photos`, method: 'GET', signal},
    options,
  )
}

export const getGetAlbumPhotosQueryKey = (id?: number) => {
  return [`/albums/${id}/photos`] as const
}

export const getGetAlbumPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumPhotos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumPhotosQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlbumPhotos>>> = ({
    signal,
  }) => getAlbumPhotos(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getAlbumPhotos>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetAlbumPhotosQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAlbumPhotos>>
>
export type GetAlbumPhotosQueryError = ErrorType<unknown>

export function useGetAlbumPhotos<
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumPhotos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAlbumPhotos>>,
          TError,
          Awaited<ReturnType<typeof getAlbumPhotos>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbumPhotos<
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumPhotos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAlbumPhotos>>,
          TError,
          Awaited<ReturnType<typeof getAlbumPhotos>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetAlbumPhotos<
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumPhotos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get photos for an album
 */

export function useGetAlbumPhotos<
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAlbumPhotos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAlbumPhotosQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetAlbumPhotosSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAlbumPhotosQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlbumPhotos>>> = ({
    signal,
  }) => getAlbumPhotos(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAlbumPhotos>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetAlbumPhotosSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAlbumPhotos>>
>
export type GetAlbumPhotosSuspenseQueryError = ErrorType<unknown>

export function useGetAlbumPhotosSuspense<
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbumPhotosSuspense<
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAlbumPhotosSuspense<
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get photos for an album
 */

export function useGetAlbumPhotosSuspense<
  TData = Awaited<ReturnType<typeof getAlbumPhotos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAlbumPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAlbumPhotosSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
