/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * JSONPlaceholder API
 * Free fake REST API for testing and prototyping
 * OpenAPI spec version: 1.0.0
 */
export interface Post {
  /** Post ID */
  id: number
  /** User ID who created the post */
  userId: number
  /** Post title */
  title: string
  /** Post content */
  body: string
}

export interface PostInput {
  /** User ID who is creating the post */
  userId: number
  /** Post title */
  title: string
  /** Post content */
  body: string
}

export interface PostPatch {
  /** User ID who created the post */
  userId?: number
  /** Post title */
  title?: string
  /** Post content */
  body?: string
}

export interface Comment {
  /** Comment ID */
  id: number
  /** Post ID this comment belongs to */
  postId: number
  /** Comment name/title */
  name: string
  /** Email of the commenter */
  email: string
  /** Comment content */
  body: string
}

export interface CommentInput {
  /** Post ID this comment belongs to */
  postId: number
  /** Comment name/title */
  name: string
  /** Email of the commenter */
  email: string
  /** Comment content */
  body: string
}

export interface CommentPatch {
  /** Post ID this comment belongs to */
  postId?: number
  /** Comment name/title */
  name?: string
  /** Email of the commenter */
  email?: string
  /** Comment content */
  body?: string
}

export interface Album {
  /** Album ID */
  id: number
  /** User ID who created the album */
  userId: number
  /** Album title */
  title: string
}

export interface AlbumInput {
  /** User ID who is creating the album */
  userId: number
  /** Album title */
  title: string
}

export interface AlbumPatch {
  /** User ID who created the album */
  userId?: number
  /** Album title */
  title?: string
}

export interface Photo {
  /** Photo ID */
  id: number
  /** Album ID this photo belongs to */
  albumId: number
  /** Photo title */
  title: string
  /** Full size photo URL */
  url: string
  /** Thumbnail photo URL */
  thumbnailUrl: string
}

export interface PhotoInput {
  /** Album ID this photo belongs to */
  albumId: number
  /** Photo title */
  title: string
  /** Full size photo URL */
  url: string
  /** Thumbnail photo URL */
  thumbnailUrl: string
}

export interface PhotoPatch {
  /** Album ID this photo belongs to */
  albumId?: number
  /** Photo title */
  title?: string
  /** Full size photo URL */
  url?: string
  /** Thumbnail photo URL */
  thumbnailUrl?: string
}

export interface Todo {
  /** Todo ID */
  id: number
  /** User ID who created the todo */
  userId: number
  /** Todo title */
  title: string
  /** Whether the todo is completed */
  completed: boolean
}

export interface TodoInput {
  /** User ID who is creating the todo */
  userId: number
  /** Todo title */
  title: string
  /** Whether the todo is completed */
  completed: boolean
}

export interface TodoPatch {
  /** User ID who created the todo */
  userId?: number
  /** Todo title */
  title?: string
  /** Whether the todo is completed */
  completed?: boolean
}

export interface User {
  /** User ID */
  id: number
  /** User's full name */
  name: string
  /** Username */
  username: string
  /** User's email */
  email: string
  address?: Address
  /** User's phone number */
  phone?: string
  /** User's website */
  website?: string
  company?: Company
}

export interface UserInput {
  /** User's full name */
  name: string
  /** Username */
  username: string
  /** User's email */
  email: string
  address?: AddressInput
  /** User's phone number */
  phone?: string
  /** User's website */
  website?: string
  company?: CompanyInput
}

export interface UserPatch {
  /** User's full name */
  name?: string
  /** Username */
  username?: string
  /** User's email */
  email?: string
  address?: AddressInput
  /** User's phone number */
  phone?: string
  /** User's website */
  website?: string
  company?: CompanyInput
}

export interface Address {
  /** Street address */
  street?: string
  /** Suite/Apartment number */
  suite?: string
  /** City */
  city?: string
  /** Zip/Postal code */
  zipcode?: string
  geo?: Geo
}

export interface AddressInput {
  /** Street address */
  street?: string
  /** Suite/Apartment number */
  suite?: string
  /** City */
  city?: string
  /** Zip/Postal code */
  zipcode?: string
  geo?: GeoInput
}

export interface Geo {
  /** Latitude */
  lat?: string
  /** Longitude */
  lng?: string
}

export interface GeoInput {
  /** Latitude */
  lat?: string
  /** Longitude */
  lng?: string
}

export interface Company {
  /** Company name */
  name?: string
  /** Company catch phrase */
  catchPhrase?: string
  /** Company business statement */
  bs?: string
}

export interface CompanyInput {
  /** Company name */
  name?: string
  /** Company catch phrase */
  catchPhrase?: string
  /** Company business statement */
  bs?: string
}

export type GetPostsParams = {
  /**
   * Filter posts by user ID
   */
  userId?: number
  /**
   * Limit the number of results
   */
  _limit?: number
  /**
   * Page number for pagination
   */
  _page?: number
}

export type GetCommentsParams = {
  /**
   * Filter comments by post ID
   */
  postId?: number
  /**
   * Limit the number of results
   */
  _limit?: number
  /**
   * Page number for pagination
   */
  _page?: number
}

export type GetAlbumsParams = {
  /**
   * Filter albums by user ID
   */
  userId?: number
  /**
   * Limit the number of results
   */
  _limit?: number
  /**
   * Page number for pagination
   */
  _page?: number
}

export type GetPhotosParams = {
  /**
   * Filter photos by album ID
   */
  albumId?: number
  /**
   * Limit the number of results
   */
  _limit?: number
  /**
   * Page number for pagination
   */
  _page?: number
}

export type GetTodosParams = {
  /**
   * Filter todos by user ID
   */
  userId?: number
  /**
   * Limit the number of results
   */
  _limit?: number
  /**
   * Page number for pagination
   */
  _page?: number
}

export type GetUsersParams = {
  /**
   * Limit the number of results
   */
  _limit?: number
  /**
   * Page number for pagination
   */
  _page?: number
}
