/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * JSONPlaceholder API
 * Free fake REST API for testing and prototyping
 * OpenAPI spec version: 1.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  Comment,
  CommentInput,
  CommentPatch,
  GetCommentsParams,
} from './api.generated.schemas'

import {axiosInstance} from '../axios'
import type {ErrorType, BodyType} from '../axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Returns a list of comments
 * @summary Get all comments
 */
export const getComments = (
  params?: GetCommentsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Comment[]>(
    {url: `/comments`, method: 'GET', params, signal},
    options,
  )
}

export const getGetCommentsQueryKey = (params?: GetCommentsParams) => {
  return [`/comments`, ...(params ? [params] : [])] as const
}

export const getGetCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCommentsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getComments>>> = ({
    signal,
  }) => getComments(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getComments>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getComments>>
>
export type GetCommentsQueryError = ErrorType<unknown>

export function useGetComments<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCommentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComments>>,
          TError,
          Awaited<ReturnType<typeof getComments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetComments<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComments>>,
          TError,
          Awaited<ReturnType<typeof getComments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetComments<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get all comments
 */

export function useGetComments<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getComments>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetCommentsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetCommentsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCommentsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCommentsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getComments>>> = ({
    signal,
  }) => getComments(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getComments>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetCommentsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getComments>>
>
export type GetCommentsSuspenseQueryError = ErrorType<unknown>

export function useGetCommentsSuspense<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCommentsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCommentsSuspense<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCommentsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCommentsSuspense<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCommentsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all comments
 */

export function useGetCommentsSuspense<
  TData = Awaited<ReturnType<typeof getComments>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCommentsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetCommentsSuspenseQueryOptions(params, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Creates a new comment
 * @summary Create a new comment
 */
export const createComment = (
  commentInput: BodyType<CommentInput>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Comment>(
    {
      url: `/comments`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: commentInput,
      signal,
    },
    options,
  )
}

export const getCreateCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createComment>>,
    TError,
    {data: BodyType<CommentInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  {data: BodyType<CommentInput>},
  TContext
> => {
  const mutationKey = ['createComment']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createComment>>,
    {data: BodyType<CommentInput>}
  > = (props) => {
    const {data} = props ?? {}

    return createComment(data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type CreateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createComment>>
>
export type CreateCommentMutationBody = BodyType<CommentInput>
export type CreateCommentMutationError = ErrorType<unknown>

/**
 * @summary Create a new comment
 */
export const useCreateComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createComment>>,
      TError,
      {data: BodyType<CommentInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  {data: BodyType<CommentInput>},
  TContext
> => {
  const mutationOptions = getCreateCommentMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Returns a single comment
 * @summary Get a comment by ID
 */
export const getCommentById = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Comment>(
    {url: `/comments/${id}`, method: 'GET', signal},
    options,
  )
}

export const getGetCommentByIdQueryKey = (id?: number) => {
  return [`/comments/${id}`] as const
}

export const getGetCommentByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCommentById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCommentByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommentById>>> = ({
    signal,
  }) => getCommentById(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getCommentById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetCommentByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCommentById>>
>
export type GetCommentByIdQueryError = ErrorType<null>

export function useGetCommentById<
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCommentById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommentById>>,
          TError,
          Awaited<ReturnType<typeof getCommentById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCommentById<
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCommentById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommentById>>,
          TError,
          Awaited<ReturnType<typeof getCommentById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetCommentById<
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCommentById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get a comment by ID
 */

export function useGetCommentById<
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCommentById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetCommentByIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetCommentByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCommentById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCommentByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommentById>>> = ({
    signal,
  }) => getCommentById(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCommentById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetCommentByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCommentById>>
>
export type GetCommentByIdSuspenseQueryError = ErrorType<null>

export function useGetCommentByIdSuspense<
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCommentById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCommentByIdSuspense<
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCommentById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCommentByIdSuspense<
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCommentById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a comment by ID
 */

export function useGetCommentByIdSuspense<
  TData = Awaited<ReturnType<typeof getCommentById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCommentById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetCommentByIdSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Updates an existing comment (replaces all fields)
 * @summary Update a comment
 */
export const updateComment = (
  id: number,
  commentInput: BodyType<CommentInput>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<Comment>(
    {
      url: `/comments/${id}`,
      method: 'PUT',
      headers: {'Content-Type': 'application/json'},
      data: commentInput,
    },
    options,
  )
}

export const getUpdateCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateComment>>,
    TError,
    {id: number; data: BodyType<CommentInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  {id: number; data: BodyType<CommentInput>},
  TContext
> => {
  const mutationKey = ['updateComment']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateComment>>,
    {id: number; data: BodyType<CommentInput>}
  > = (props) => {
    const {id, data} = props ?? {}

    return updateComment(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type UpdateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateComment>>
>
export type UpdateCommentMutationBody = BodyType<CommentInput>
export type UpdateCommentMutationError = ErrorType<unknown>

/**
 * @summary Update a comment
 */
export const useUpdateComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateComment>>,
      TError,
      {id: number; data: BodyType<CommentInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  {id: number; data: BodyType<CommentInput>},
  TContext
> => {
  const mutationOptions = getUpdateCommentMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Updates specific fields of an existing comment
 * @summary Partially update a comment
 */
export const patchComment = (
  id: number,
  commentPatch: BodyType<CommentPatch>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<Comment>(
    {
      url: `/comments/${id}`,
      method: 'PATCH',
      headers: {'Content-Type': 'application/json'},
      data: commentPatch,
    },
    options,
  )
}

export const getPatchCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchComment>>,
    TError,
    {id: number; data: BodyType<CommentPatch>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchComment>>,
  TError,
  {id: number; data: BodyType<CommentPatch>},
  TContext
> => {
  const mutationKey = ['patchComment']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchComment>>,
    {id: number; data: BodyType<CommentPatch>}
  > = (props) => {
    const {id, data} = props ?? {}

    return patchComment(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type PatchCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchComment>>
>
export type PatchCommentMutationBody = BodyType<CommentPatch>
export type PatchCommentMutationError = ErrorType<unknown>

/**
 * @summary Partially update a comment
 */
export const usePatchComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchComment>>,
      TError,
      {id: number; data: BodyType<CommentPatch>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchComment>>,
  TError,
  {id: number; data: BodyType<CommentPatch>},
  TContext
> => {
  const mutationOptions = getPatchCommentMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Deletes a comment
 * @summary Delete a comment
 */
export const deleteComment = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    {url: `/comments/${id}`, method: 'DELETE'},
    options,
  )
}

export const getDeleteCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteComment>>,
    TError,
    {id: number},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationKey = ['deleteComment']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteComment>>,
    {id: number}
  > = (props) => {
    const {id} = props ?? {}

    return deleteComment(id, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type DeleteCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteComment>>
>

export type DeleteCommentMutationError = ErrorType<unknown>

/**
 * @summary Delete a comment
 */
export const useDeleteComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteComment>>,
      TError,
      {id: number},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationOptions = getDeleteCommentMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
