/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * JSONPlaceholder API
 * Free fake REST API for testing and prototyping
 * OpenAPI spec version: 1.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  GetPhotosParams,
  Photo,
  PhotoInput,
  PhotoPatch,
} from './api.generated.schemas'

import {axiosInstance} from '../axios'
import type {ErrorType, BodyType} from '../axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Returns a list of photos
 * @summary Get all photos
 */
export const getPhotos = (
  params?: GetPhotosParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Photo[]>(
    {url: `/photos`, method: 'GET', params, signal},
    options,
  )
}

export const getGetPhotosQueryKey = (params?: GetPhotosParams) => {
  return [`/photos`, ...(params ? [params] : [])] as const
}

export const getGetPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPhotosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotosQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhotos>>> = ({
    signal,
  }) => getPhotos(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getPhotos>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPhotosQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPhotos>>
>
export type GetPhotosQueryError = ErrorType<unknown>

export function useGetPhotos<
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetPhotosParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhotos>>,
          TError,
          Awaited<ReturnType<typeof getPhotos>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPhotos<
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPhotosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhotos>>,
          TError,
          Awaited<ReturnType<typeof getPhotos>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetPhotos<
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPhotosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get all photos
 */

export function useGetPhotos<
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPhotosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPhotosQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetPhotosSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPhotosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotosQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhotos>>> = ({
    signal,
  }) => getPhotos(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getPhotos>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPhotosSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPhotos>>
>
export type GetPhotosSuspenseQueryError = ErrorType<unknown>

export function useGetPhotosSuspense<
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetPhotosParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPhotosSuspense<
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPhotosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPhotosSuspense<
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPhotosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all photos
 */

export function useGetPhotosSuspense<
  TData = Awaited<ReturnType<typeof getPhotos>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPhotosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPhotosSuspenseQueryOptions(params, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Creates a new photo
 * @summary Create a new photo
 */
export const createPhoto = (
  photoInput: BodyType<PhotoInput>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Photo>(
    {
      url: `/photos`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: photoInput,
      signal,
    },
    options,
  )
}

export const getCreatePhotoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPhoto>>,
    TError,
    {data: BodyType<PhotoInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPhoto>>,
  TError,
  {data: BodyType<PhotoInput>},
  TContext
> => {
  const mutationKey = ['createPhoto']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPhoto>>,
    {data: BodyType<PhotoInput>}
  > = (props) => {
    const {data} = props ?? {}

    return createPhoto(data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type CreatePhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPhoto>>
>
export type CreatePhotoMutationBody = BodyType<PhotoInput>
export type CreatePhotoMutationError = ErrorType<unknown>

/**
 * @summary Create a new photo
 */
export const useCreatePhoto = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPhoto>>,
      TError,
      {data: BodyType<PhotoInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPhoto>>,
  TError,
  {data: BodyType<PhotoInput>},
  TContext
> => {
  const mutationOptions = getCreatePhotoMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Returns a single photo
 * @summary Get a photo by ID
 */
export const getPhotoById = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Photo>(
    {url: `/photos/${id}`, method: 'GET', signal},
    options,
  )
}

export const getGetPhotoByIdQueryKey = (id?: number) => {
  return [`/photos/${id}`] as const
}

export const getGetPhotoByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotoById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotoByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhotoById>>> = ({
    signal,
  }) => getPhotoById(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getPhotoById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPhotoByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPhotoById>>
>
export type GetPhotoByIdQueryError = ErrorType<null>

export function useGetPhotoById<
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotoById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhotoById>>,
          TError,
          Awaited<ReturnType<typeof getPhotoById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPhotoById<
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotoById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhotoById>>,
          TError,
          Awaited<ReturnType<typeof getPhotoById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetPhotoById<
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotoById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get a photo by ID
 */

export function useGetPhotoById<
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPhotoById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPhotoByIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetPhotoByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotoById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPhotoByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhotoById>>> = ({
    signal,
  }) => getPhotoById(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getPhotoById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPhotoByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPhotoById>>
>
export type GetPhotoByIdSuspenseQueryError = ErrorType<null>

export function useGetPhotoByIdSuspense<
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotoById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPhotoByIdSuspense<
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotoById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPhotoByIdSuspense<
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotoById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a photo by ID
 */

export function useGetPhotoByIdSuspense<
  TData = Awaited<ReturnType<typeof getPhotoById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPhotoById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPhotoByIdSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Updates an existing photo (replaces all fields)
 * @summary Update a photo
 */
export const updatePhoto = (
  id: number,
  photoInput: BodyType<PhotoInput>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<Photo>(
    {
      url: `/photos/${id}`,
      method: 'PUT',
      headers: {'Content-Type': 'application/json'},
      data: photoInput,
    },
    options,
  )
}

export const getUpdatePhotoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePhoto>>,
    TError,
    {id: number; data: BodyType<PhotoInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePhoto>>,
  TError,
  {id: number; data: BodyType<PhotoInput>},
  TContext
> => {
  const mutationKey = ['updatePhoto']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePhoto>>,
    {id: number; data: BodyType<PhotoInput>}
  > = (props) => {
    const {id, data} = props ?? {}

    return updatePhoto(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type UpdatePhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePhoto>>
>
export type UpdatePhotoMutationBody = BodyType<PhotoInput>
export type UpdatePhotoMutationError = ErrorType<unknown>

/**
 * @summary Update a photo
 */
export const useUpdatePhoto = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePhoto>>,
      TError,
      {id: number; data: BodyType<PhotoInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePhoto>>,
  TError,
  {id: number; data: BodyType<PhotoInput>},
  TContext
> => {
  const mutationOptions = getUpdatePhotoMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Updates specific fields of an existing photo
 * @summary Partially update a photo
 */
export const patchPhoto = (
  id: number,
  photoPatch: BodyType<PhotoPatch>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<Photo>(
    {
      url: `/photos/${id}`,
      method: 'PATCH',
      headers: {'Content-Type': 'application/json'},
      data: photoPatch,
    },
    options,
  )
}

export const getPatchPhotoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchPhoto>>,
    TError,
    {id: number; data: BodyType<PhotoPatch>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchPhoto>>,
  TError,
  {id: number; data: BodyType<PhotoPatch>},
  TContext
> => {
  const mutationKey = ['patchPhoto']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchPhoto>>,
    {id: number; data: BodyType<PhotoPatch>}
  > = (props) => {
    const {id, data} = props ?? {}

    return patchPhoto(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type PatchPhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchPhoto>>
>
export type PatchPhotoMutationBody = BodyType<PhotoPatch>
export type PatchPhotoMutationError = ErrorType<unknown>

/**
 * @summary Partially update a photo
 */
export const usePatchPhoto = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchPhoto>>,
      TError,
      {id: number; data: BodyType<PhotoPatch>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchPhoto>>,
  TError,
  {id: number; data: BodyType<PhotoPatch>},
  TContext
> => {
  const mutationOptions = getPatchPhotoMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Deletes a photo
 * @summary Delete a photo
 */
export const deletePhoto = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>({url: `/photos/${id}`, method: 'DELETE'}, options)
}

export const getDeletePhotoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePhoto>>,
    TError,
    {id: number},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePhoto>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationKey = ['deletePhoto']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePhoto>>,
    {id: number}
  > = (props) => {
    const {id} = props ?? {}

    return deletePhoto(id, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type DeletePhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePhoto>>
>

export type DeletePhotoMutationError = ErrorType<unknown>

/**
 * @summary Delete a photo
 */
export const useDeletePhoto = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePhoto>>,
      TError,
      {id: number},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePhoto>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationOptions = getDeletePhotoMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
