/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * JSONPlaceholder API
 * Free fake REST API for testing and prototyping
 * OpenAPI spec version: 1.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  Comment,
  GetPostsParams,
  Post,
  PostInput,
  PostPatch,
} from './api.generated.schemas'

import {axiosInstance} from '../axios'
import type {ErrorType, BodyType} from '../axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Returns a list of posts
 * @summary Get all posts
 */
export const getPosts = (
  params?: GetPostsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Post[]>(
    {url: `/posts`, method: 'GET', params, signal},
    options,
  )
}

export const getGetPostsQueryKey = (params?: GetPostsParams) => {
  return [`/posts`, ...(params ? [params] : [])] as const
}

export const getGetPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({
    signal,
  }) => getPosts(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPosts>>
>
export type GetPostsQueryError = ErrorType<unknown>

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get all posts
 */

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPostsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetPostsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({
    signal,
  }) => getPosts(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPostsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPosts>>
>
export type GetPostsSuspenseQueryError = ErrorType<unknown>

export function useGetPostsSuspense<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetPostsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPostsSuspense<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPostsSuspense<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all posts
 */

export function useGetPostsSuspense<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPostsSuspenseQueryOptions(params, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Creates a new post
 * @summary Create a new post
 */
export const createPost = (
  postInput: BodyType<PostInput>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Post>(
    {
      url: `/posts`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: postInput,
      signal,
    },
    options,
  )
}

export const getCreatePostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPost>>,
    TError,
    {data: BodyType<PostInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPost>>,
  TError,
  {data: BodyType<PostInput>},
  TContext
> => {
  const mutationKey = ['createPost']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPost>>,
    {data: BodyType<PostInput>}
  > = (props) => {
    const {data} = props ?? {}

    return createPost(data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type CreatePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPost>>
>
export type CreatePostMutationBody = BodyType<PostInput>
export type CreatePostMutationError = ErrorType<unknown>

/**
 * @summary Create a new post
 */
export const useCreatePost = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPost>>,
      TError,
      {data: BodyType<PostInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPost>>,
  TError,
  {data: BodyType<PostInput>},
  TContext
> => {
  const mutationOptions = getCreatePostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Returns a single post
 * @summary Get a post by ID
 */
export const getPostById = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Post>(
    {url: `/posts/${id}`, method: 'GET', signal},
    options,
  )
}

export const getGetPostByIdQueryKey = (id?: number) => {
  return [`/posts/${id}`] as const
}

export const getGetPostByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPostByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostById>>> = ({
    signal,
  }) => getPostById(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getPostById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPostByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostById>>
>
export type GetPostByIdQueryError = ErrorType<null>

export function useGetPostById<
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostById>>,
          TError,
          Awaited<ReturnType<typeof getPostById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPostById<
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostById>>,
          TError,
          Awaited<ReturnType<typeof getPostById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetPostById<
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get a post by ID
 */

export function useGetPostById<
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPostByIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetPostByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPostByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostById>>> = ({
    signal,
  }) => getPostById(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getPostById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPostByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostById>>
>
export type GetPostByIdSuspenseQueryError = ErrorType<null>

export function useGetPostByIdSuspense<
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPostByIdSuspense<
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPostByIdSuspense<
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a post by ID
 */

export function useGetPostByIdSuspense<
  TData = Awaited<ReturnType<typeof getPostById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPostByIdSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Updates an existing post (replaces all fields)
 * @summary Update a post
 */
export const updatePost = (
  id: number,
  postInput: BodyType<PostInput>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<Post>(
    {
      url: `/posts/${id}`,
      method: 'PUT',
      headers: {'Content-Type': 'application/json'},
      data: postInput,
    },
    options,
  )
}

export const getUpdatePostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePost>>,
    TError,
    {id: number; data: BodyType<PostInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePost>>,
  TError,
  {id: number; data: BodyType<PostInput>},
  TContext
> => {
  const mutationKey = ['updatePost']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePost>>,
    {id: number; data: BodyType<PostInput>}
  > = (props) => {
    const {id, data} = props ?? {}

    return updatePost(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type UpdatePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePost>>
>
export type UpdatePostMutationBody = BodyType<PostInput>
export type UpdatePostMutationError = ErrorType<unknown>

/**
 * @summary Update a post
 */
export const useUpdatePost = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePost>>,
      TError,
      {id: number; data: BodyType<PostInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePost>>,
  TError,
  {id: number; data: BodyType<PostInput>},
  TContext
> => {
  const mutationOptions = getUpdatePostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Updates specific fields of an existing post
 * @summary Partially update a post
 */
export const patchPost = (
  id: number,
  postPatch: BodyType<PostPatch>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<Post>(
    {
      url: `/posts/${id}`,
      method: 'PATCH',
      headers: {'Content-Type': 'application/json'},
      data: postPatch,
    },
    options,
  )
}

export const getPatchPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchPost>>,
    TError,
    {id: number; data: BodyType<PostPatch>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchPost>>,
  TError,
  {id: number; data: BodyType<PostPatch>},
  TContext
> => {
  const mutationKey = ['patchPost']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchPost>>,
    {id: number; data: BodyType<PostPatch>}
  > = (props) => {
    const {id, data} = props ?? {}

    return patchPost(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type PatchPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchPost>>
>
export type PatchPostMutationBody = BodyType<PostPatch>
export type PatchPostMutationError = ErrorType<unknown>

/**
 * @summary Partially update a post
 */
export const usePatchPost = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchPost>>,
      TError,
      {id: number; data: BodyType<PostPatch>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchPost>>,
  TError,
  {id: number; data: BodyType<PostPatch>},
  TContext
> => {
  const mutationOptions = getPatchPostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Deletes a post
 * @summary Delete a post
 */
export const deletePost = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>({url: `/posts/${id}`, method: 'DELETE'}, options)
}

export const getDeletePostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePost>>,
    TError,
    {id: number},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePost>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationKey = ['deletePost']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePost>>,
    {id: number}
  > = (props) => {
    const {id} = props ?? {}

    return deletePost(id, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type DeletePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePost>>
>

export type DeletePostMutationError = ErrorType<unknown>

/**
 * @summary Delete a post
 */
export const useDeletePost = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePost>>,
      TError,
      {id: number},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePost>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationOptions = getDeletePostMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Returns all comments for a specific post
 * @summary Get comments for a post
 */
export const getPostComments = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Comment[]>(
    {url: `/posts/${id}/comments`, method: 'GET', signal},
    options,
  )
}

export const getGetPostCommentsQueryKey = (id?: number) => {
  return [`/posts/${id}/comments`] as const
}

export const getGetPostCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPostCommentsQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostComments>>> = ({
    signal,
  }) => getPostComments(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getPostComments>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPostCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostComments>>
>
export type GetPostCommentsQueryError = ErrorType<unknown>

export function useGetPostComments<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostComments>>,
          TError,
          Awaited<ReturnType<typeof getPostComments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPostComments<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostComments>>,
          TError,
          Awaited<ReturnType<typeof getPostComments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetPostComments<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get comments for a post
 */

export function useGetPostComments<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPostCommentsQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetPostCommentsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPostCommentsQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostComments>>> = ({
    signal,
  }) => getPostComments(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getPostComments>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetPostCommentsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostComments>>
>
export type GetPostCommentsSuspenseQueryError = ErrorType<unknown>

export function useGetPostCommentsSuspense<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPostCommentsSuspense<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPostCommentsSuspense<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get comments for a post
 */

export function useGetPostCommentsSuspense<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPostCommentsSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
