/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * JSONPlaceholder API
 * Free fake REST API for testing and prototyping
 * OpenAPI spec version: 1.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type {
  Album,
  GetUsersParams,
  Post,
  Todo,
  User,
  UserInput,
  UserPatch,
} from './api.generated.schemas'

import {axiosInstance} from '../axios'
import type {ErrorType, BodyType} from '../axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Returns a list of users
 * @summary Get all users
 */
export const getUsers = (
  params?: GetUsersParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<User[]>(
    {url: `/users`, method: 'GET', params, signal},
    options,
  )
}

export const getGetUsersQueryKey = (params?: GetUsersParams) => {
  return [`/users`, ...(params ? [params] : [])] as const
}

export const getGetUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({
    signal,
  }) => getUsers(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getUsers>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsers>>
>
export type GetUsersQueryError = ErrorType<unknown>

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get all users
 */

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUsersQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetUsersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({
    signal,
  }) => getUsers(params, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getUsers>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUsersSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsers>>
>
export type GetUsersSuspenseQueryError = ErrorType<unknown>

export function useGetUsersSuspense<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetUsersParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUsersSuspense<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUsersSuspense<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all users
 */

export function useGetUsersSuspense<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetUsersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUsersSuspenseQueryOptions(params, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Creates a new user
 * @summary Create a new user
 */
export const createUser = (
  userInput: BodyType<UserInput>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<User>(
    {
      url: `/users`,
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: userInput,
      signal,
    },
    options,
  )
}

export const getCreateUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    {data: BodyType<UserInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUser>>,
  TError,
  {data: BodyType<UserInput>},
  TContext
> => {
  const mutationKey = ['createUser']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUser>>,
    {data: BodyType<UserInput>}
  > = (props) => {
    const {data} = props ?? {}

    return createUser(data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type CreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUser>>
>
export type CreateUserMutationBody = BodyType<UserInput>
export type CreateUserMutationError = ErrorType<unknown>

/**
 * @summary Create a new user
 */
export const useCreateUser = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createUser>>,
      TError,
      {data: BodyType<UserInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createUser>>,
  TError,
  {data: BodyType<UserInput>},
  TContext
> => {
  const mutationOptions = getCreateUserMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Returns a single user
 * @summary Get a user by ID
 */
export const getUserById = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<User>(
    {url: `/users/${id}`, method: 'GET', signal},
    options,
  )
}

export const getGetUserByIdQueryKey = (id?: number) => {
  return [`/users/${id}`] as const
}

export const getGetUserByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({
    signal,
  }) => getUserById(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getUserById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUserByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>
export type GetUserByIdQueryError = ErrorType<null>

export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserById>>,
          TError,
          Awaited<ReturnType<typeof getUserById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get a user by ID
 */

export function useGetUserById<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserByIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetUserByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserByIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({
    signal,
  }) => getUserById(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getUserById>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUserByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>
export type GetUserByIdSuspenseQueryError = ErrorType<null>

export function useGetUserByIdSuspense<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserByIdSuspense<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserByIdSuspense<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a user by ID
 */

export function useGetUserByIdSuspense<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = ErrorType<null>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserByIdSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Updates an existing user (replaces all fields)
 * @summary Update a user
 */
export const updateUser = (
  id: number,
  userInput: BodyType<UserInput>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<User>(
    {
      url: `/users/${id}`,
      method: 'PUT',
      headers: {'Content-Type': 'application/json'},
      data: userInput,
    },
    options,
  )
}

export const getUpdateUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    {id: number; data: BodyType<UserInput>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  {id: number; data: BodyType<UserInput>},
  TContext
> => {
  const mutationKey = ['updateUser']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    {id: number; data: BodyType<UserInput>}
  > = (props) => {
    const {id, data} = props ?? {}

    return updateUser(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>
export type UpdateUserMutationBody = BodyType<UserInput>
export type UpdateUserMutationError = ErrorType<unknown>

/**
 * @summary Update a user
 */
export const useUpdateUser = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUser>>,
      TError,
      {id: number; data: BodyType<UserInput>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  {id: number; data: BodyType<UserInput>},
  TContext
> => {
  const mutationOptions = getUpdateUserMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Updates specific fields of an existing user
 * @summary Partially update a user
 */
export const patchUser = (
  id: number,
  userPatch: BodyType<UserPatch>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<User>(
    {
      url: `/users/${id}`,
      method: 'PATCH',
      headers: {'Content-Type': 'application/json'},
      data: userPatch,
    },
    options,
  )
}

export const getPatchUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchUser>>,
    TError,
    {id: number; data: BodyType<UserPatch>},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchUser>>,
  TError,
  {id: number; data: BodyType<UserPatch>},
  TContext
> => {
  const mutationKey = ['patchUser']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchUser>>,
    {id: number; data: BodyType<UserPatch>}
  > = (props) => {
    const {id, data} = props ?? {}

    return patchUser(id, data, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type PatchUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchUser>>
>
export type PatchUserMutationBody = BodyType<UserPatch>
export type PatchUserMutationError = ErrorType<unknown>

/**
 * @summary Partially update a user
 */
export const usePatchUser = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchUser>>,
      TError,
      {id: number; data: BodyType<UserPatch>},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchUser>>,
  TError,
  {id: number; data: BodyType<UserPatch>},
  TContext
> => {
  const mutationOptions = getPatchUserMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Deletes a user
 * @summary Delete a user
 */
export const deleteUser = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>({url: `/users/${id}`, method: 'DELETE'}, options)
}

export const getDeleteUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    {id: number},
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationKey = ['deleteUser']
  const {mutation: mutationOptions, request: requestOptions} = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : {...options, mutation: {...options.mutation, mutationKey}}
    : {mutation: {mutationKey}, request: undefined}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUser>>,
    {id: number}
  > = (props) => {
    const {id} = props ?? {}

    return deleteUser(id, requestOptions)
  }

  return {mutationFn, ...mutationOptions}
}

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>

export type DeleteUserMutationError = ErrorType<unknown>

/**
 * @summary Delete a user
 */
export const useDeleteUser = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      {id: number},
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationOptions = getDeleteUserMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Returns all posts for a specific user
 * @summary Get posts for a user
 */
export const getUserPosts = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Post[]>(
    {url: `/users/${id}/posts`, method: 'GET', signal},
    options,
  )
}

export const getGetUserPostsQueryKey = (id?: number) => {
  return [`/users/${id}/posts`] as const
}

export const getGetUserPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserPostsQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserPosts>>> = ({
    signal,
  }) => getUserPosts(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getUserPosts>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUserPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserPosts>>
>
export type GetUserPostsQueryError = ErrorType<unknown>

export function useGetUserPosts<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPosts>>,
          TError,
          Awaited<ReturnType<typeof getUserPosts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserPosts<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPosts>>,
          TError,
          Awaited<ReturnType<typeof getUserPosts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetUserPosts<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get posts for a user
 */

export function useGetUserPosts<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserPostsQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetUserPostsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserPostsQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserPosts>>> = ({
    signal,
  }) => getUserPosts(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getUserPosts>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUserPostsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserPosts>>
>
export type GetUserPostsSuspenseQueryError = ErrorType<unknown>

export function useGetUserPostsSuspense<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserPostsSuspense<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserPostsSuspense<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get posts for a user
 */

export function useGetUserPostsSuspense<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserPostsSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Returns all albums for a specific user
 * @summary Get albums for a user
 */
export const getUserAlbums = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Album[]>(
    {url: `/users/${id}/albums`, method: 'GET', signal},
    options,
  )
}

export const getGetUserAlbumsQueryKey = (id?: number) => {
  return [`/users/${id}/albums`] as const
}

export const getGetUserAlbumsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserAlbums>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserAlbumsQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserAlbums>>> = ({
    signal,
  }) => getUserAlbums(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getUserAlbums>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUserAlbumsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserAlbums>>
>
export type GetUserAlbumsQueryError = ErrorType<unknown>

export function useGetUserAlbums<
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserAlbums>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserAlbums>>,
          TError,
          Awaited<ReturnType<typeof getUserAlbums>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserAlbums<
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserAlbums>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserAlbums>>,
          TError,
          Awaited<ReturnType<typeof getUserAlbums>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetUserAlbums<
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserAlbums>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get albums for a user
 */

export function useGetUserAlbums<
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserAlbums>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserAlbumsQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetUserAlbumsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserAlbumsQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserAlbums>>> = ({
    signal,
  }) => getUserAlbums(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getUserAlbums>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUserAlbumsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserAlbums>>
>
export type GetUserAlbumsSuspenseQueryError = ErrorType<unknown>

export function useGetUserAlbumsSuspense<
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserAlbumsSuspense<
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserAlbumsSuspense<
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get albums for a user
 */

export function useGetUserAlbumsSuspense<
  TData = Awaited<ReturnType<typeof getUserAlbums>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserAlbums>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserAlbumsSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Returns all todos for a specific user
 * @summary Get todos for a user
 */
export const getUserTodos = (
  id: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Todo[]>(
    {url: `/users/${id}/todos`, method: 'GET', signal},
    options,
  )
}

export const getGetUserTodosQueryKey = (id?: number) => {
  return [`/users/${id}/todos`] as const
}

export const getGetUserTodosQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTodos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserTodosQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserTodos>>> = ({
    signal,
  }) => getUserTodos(id, requestOptions, signal)

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof getUserTodos>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUserTodosQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserTodos>>
>
export type GetUserTodosQueryError = ErrorType<unknown>

export function useGetUserTodos<
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTodos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserTodos>>,
          TError,
          Awaited<ReturnType<typeof getUserTodos>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserTodos<
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTodos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserTodos>>,
          TError,
          Awaited<ReturnType<typeof getUserTodos>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
export function useGetUserTodos<
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTodos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>}
/**
 * @summary Get todos for a user
 */

export function useGetUserTodos<
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserTodos>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserTodosQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & {queryKey: DataTag<QueryKey, TData, TError>}

  query.queryKey = queryOptions.queryKey

  return query
}

export const getGetUserTodosSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserTodos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserTodosQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserTodos>>> = ({
    signal,
  }) => getUserTodos(id, requestOptions, signal)

  return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getUserTodos>>,
    TError,
    TData
  > & {queryKey: DataTag<QueryKey, TData, TError>}
}

export type GetUserTodosSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserTodos>>
>
export type GetUserTodosSuspenseQueryError = ErrorType<unknown>

export function useGetUserTodosSuspense<
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserTodos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserTodosSuspense<
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserTodos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserTodosSuspense<
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserTodos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get todos for a user
 */

export function useGetUserTodosSuspense<
  TData = Awaited<ReturnType<typeof getUserTodos>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserTodos>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserTodosSuspenseQueryOptions(id, options)

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
