import type {InfoObject} from 'openapi3-ts/oas30'
import type {Options} from 'orval'

import {defineConfig} from 'orval'

const header = (info: InfoObject): string[] => [
  `eslint-disable`,
  `Generated by orval 🍺`,
  `Do not edit manually.`,
  ...(info.title ? [info.title] : []),
  ...(info.description ? [info.description] : []),
  ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
]

const defaultOutputOptions: Options['output'] = {
  mode: 'tags',
  prettier: true,
  client: 'react-query',
  clean: true,
  override: {
    header,
    mutator: {
      path: './axios.ts',
      name: 'axiosInstance',
    },
    query: {
      useSuspenseQuery: true,
    },
  },
}
export default defineConfig({
  JsonPlaceHolderAPI: {
    input: {
      target: './swagger/json-placeholder.yml',
    },
    output: {
      ...defaultOutputOptions,
      target: './api/api.generated.ts',
    },
  },
})
